POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
    "title": "Read Brandon Sanderson’s Wind and Truth Here on Reactor, Starting in July",
    "author": "Reactor",
    "url": "https://reactormag.com/read-brandon-sandersons-wind-and-truth-here-on-reactor/",
    "likes": 15
}